image: java:8

stages:
  - build

build:
  image: java:8
  tags:
  - gitlab-aws-runner
  stage: build
  script: 
  - chmod +x gradlew
  - ./gradlew clean build test
  artifacts:
    paths:
      - build/libs/slicetestexamples*.jar
